### ISSUE TITLE
events.yml

### ISSUE THREAD

**Issue by CCCCarsten** [andune/HomeSpawnPlus#101]
Hi! What is wrong with my events.yml. I want to use a **world-specific** strategy. But HSP only does "explicit default".

http://pastebin.com/CHSTT8H5

HSP is a monster ;)) ... sorry if I don't understand it at once.

Ciao, Carsten

**Comment by sorifiend** [comment]
Hi, do you have a normal config.yml?

The event.yml is just the defaults, so you need to make sure you make the changes to the config.yml file instead. So to get it all working just copy your changes into the `events` section of config.yml

**Comment by CCCCarsten** [comment]
Hi sorifiend,

thanks for your answer :).
HSP has not put a config.yml in the folder. In my humble opinion the config.yml is a part of older versions? I have read this but I don't find it yet...
Are you sure? ;)

Ciao, Carsten

**Comment by CCCCarsten** [comment]
Ha!! :))
https://github.com/andune/HomeSpawnPlus/wiki/HSP-2.0-Upgrade-Notes

**Comment by CCCCarsten** [comment]
Is there NO HELP ???

**Comment by CCCCarsten** [comment]
@andune , is it possible that my problem is caused by the "old" problem with lowercase worldnames?

**Comment by CCCCarsten** [comment]
Hi @andune : Can you confirm that this is a bug? In this case I would wait for better times ;). I don't think that there is a better plugin like yours, but I need to be sure. Ciao, Carsten

**Comment by sorifiend** [comment]
The other issue that you posted in was fixed a long time ago, and from what I can tell it should still be working. So lets get a bit more info on this so we can narrow it down.

The first thing you will need to do is set `verboseLogging` to true in the core.yml file (and in config.yml if you have one), now restart your server and open the console, then try do the action you want and copy and paste the homespawn output from the console or from server.log and paste it here.

Can you please provide Other info that may help:
Spigot version
HSP version

Edit, just noticed what I think is a big mistake in your config.
I believe the entire "World" section should be a sub section inside of events, not its own section below events.

For example, try this:

```
events:
  # strategies to use when player is joining the game
  onJoin:
    - spawnNewPlayer
    - default

#  example of world-specific strategy
  world:
    # Welten auf denen Homes gesetzt werden dürfen:
    Zentrale:
      onJoin:
      - spawnNewPlayer
      - default
      onDeath:
      - homeLocalWorld
      - spawnLocalWorld
      onHomeCommand:
      - spawnLocalWorld
      onNamedHomeCommand:
      - homeNamedHome
```

Instead of:
```
events:
  # strategies to use when player is joining the game
  onJoin:
    - spawnNewPlayer
    - default

#  example of world-specific strategy
world:
  # Welten auf denen Homes gesetzt werden dürfen:
  Zentrale:
    onJoin:
    - spawnNewPlayer
    - default
    onDeath:
    - homeLocalWorld
    - spawnLocalWorld
    onHomeCommand:
    - spawnLocalWorld
    onNamedHomeCommand:
    - homeNamedHome
```
