### ISSUE TITLE
q: how can i respawn at a random location within a min/max radius of my death location?

### ISSUE THREAD

**Issue by njdro** [andune/HomeSpawnPlus#12]
idea blatantly taken from "Ghosts" plugin.  I'd like to be able to respawn at a random location say between 40 and 100 blocks from my point of death (where 40 and 100 are variables i can set).

**Comment by soopageek** [comment]
The builds are way past build #560 at this point, obvs...  has this been implemented in 2.0 or no?  There's yet to be any documentation.  I've tried adding it as an event strategy, but I'm not having any luck with it.  Just thought I'd bump this to see what the status is.  This would be a fantastic strategy to have.

**Comment by andune** [comment]
This code is in the latest 2.0 builds, though I haven't tested it since it was written. Nothing has changed with the strategy since it was written and tested, so I'd expect it's still in good working condition. Certainly happy to take a bug report otherwise and look into it.

Documentation is sorely lacking for HSP at this point, which is unfortunate. And unless someone volunteers to start writing docs, it's unlikely to be resolved anytime soon. The docs for this feature, as linked above, are contained within the comments, so the usage is as so:

```
lastDeathRandomRadius:radius;yVariance
```

such as:

```
events:
  onDeath:
    lastDeathRandomRadius:100
```

This would spawn someone within 100 blocks of their death location. If that's not working, please turn on verboseStrategyLogging and pastebin the logs from your attempts here. That might make the error obvious to your or me from the logs, or if not, might give you the necessary information to file a bug report.

**Comment by meoso** [comment]
what if using multiverse, and want this only for one specific world?

**Comment by andune** [comment]
Then usual HSP per-world configs apply. Something like:

```
events:
  world:
    myworld:
      lastDeathRandomRadius:100
```

**Comment by andune** [comment]
The new format (latest build) for this strategy is:

```
lastDeathRandomRadius:maxRadius;minRadius;yVariance
```

For example, if you wanted players to spawn at least 50 blocks away but not more than 200, and you want them to spawn within 10 blocks of the vertical range they died in (instead of up to 200), you could use:

```
lastDeathRandomRadius:200;50;10
```

**Comment by meoso** [comment]
That's fricken awesome @andune; totally works!

```
  # strategies to use when player is respawning after a death
  world:
    my_word:
      onDeath:
      - lastDeathRandomRadius:330;80;10

  onDeath:
    - homeMultiWorld
    - spawnLocalWorld

```
