### ISSUE TITLE
Dynmap integration not showing

### ISSUE THREAD

**Issue by curtisprevo** [andune/HomeSpawnPlus#58]
I've set dynmap: enabled: true and spawns: enable: true.  It shows that dynmap integration loads properly in the console.  My map shows a layer called "Spawns", but none of the spawns I set actually show up on the map.  My custom markers do.  Am I missing a setting?  I'm running Spigot 1.8.3 and the latest HSP.

```
dynmap:
  # Set to true to enable this module, otherwise it is completely
  # disabled
  enabled: true

  update:
    # Seconds between position updates
    period: 300.0
    
  layer:
    homes:
      enable: false
      # by default, HSP will render the default home. You can also tell
      # it to render any bed homes or even all named homes
      include-bed-home: false
      include-named-homes: true
      name: "Homes"
      # Make home layer hidden by default
      hidebydefault: false
      # ordering priority in layer menu (low goes before high - default is 0)
      layerprio: 20
      # (optional) set minimum zoom level when mob icons should be visible (0=default, any zoom)
      minzoom: 0
      # Default icon for home markers
      deficon: pin
      # Label format - substitute %name% for player's name
      labelfmt: "%name%"
      # (optional) List of visible homes (by user ID) - if non-empty, only these will be shown.
      # To show all homes on a given world, include "world:<worldname>" in the string list
      visiblemarkers: []
      # (optional) List of hidden homes (by user ID)
      # To hide all homes on a given world, include "world:<worldname>" in the string list
      hiddenmarkers: []
      # (optional) If set to true, only show homes of online players
      online-only: false
    spawns:
      enable: true
      # by default, HSP will render named spawns. You can disable it here, or
      # create separate layers using this flag
      include-named-spawns: true
      name: "Spawns"
      # Make warp layer hidden by default
      hidebydefault: false
      # ordering priority in layer menu (low goes before high - default is 0)
      layerprio: 21
      # (optional) set minimum zoom level when mob icons should be visible (0=default, any zoom)
      minzoom: 0
      # Default icon for warp markers
      deficon: portal
      # Label format - substitute %name% for warp's name
      labelfmt: "[%name%]"
      # (optional) List of visible spawns (by spawn name) - if non-empty, only these will be shown.
      # To show all spawns on a given world, include "world:<worldname>" in the string list
      visiblemarkers: []
      # (optional) List of hidden spawns (by spawn name)
      # To hide all spawns on a given world, include "world:<worldname>" in the string list
      hiddenmarkers: []
```
