### ISSUE TITLE
per world home limits

### ISSUE THREAD

**Issue by frizzbee30** [andune/HomeSpawnPlus#65]
Hi, i don't know if this is the same issue @syrmor is having, as the odd thing is it appears to work with 'vanilla' but not Survival map  or Towny  (a clone of Survival, but I thought splitting it out may help, which it didn't). The idea is to basically break it down by rank, but have an absolute limit in vanilla of 1, with obviously a different global limit to account for staff and VIP's  (ignore staff perm mispelling  :)  ).  The perms are handled in Group manager.

http://pastebin.com/avDKqDUV

**Comment by frizzbee30** [comment]
If you can only have one permission then limit 1, followed by limit 2, how do you set the limit 2 permissions, which will be different to limit 1 (ie next VIP level etc)? Thanks

**Comment by andune** [comment]
You should only have one 'permission' section - it looks like you've duplicated it multiple times. Only one of them will apply and since you have 3 or 4, it's anybody's guess as to which one the YAML parser is picking.

It also looks like it's embedded under a world tag?  If so, that's not how it works. Here is an example structure:

```
homeLimits:
  # defaults, if nothing else applies, will be limit perWorld of 1 and 3 global
  perWorld: 1
  global: 3

  world:
    # if no permission-specific rules apply, limit would be 2 homes on Vanilla
    Vanilla:
      perWorld: 2

  permission:
    # admins have unlimited
    limit1:
      permissions: [admin]
      perWorld: -1
      global: -1

    # staff gets limit of 10 per world and 10 global
    limit2:
      permissions: [HSPSTAFF]
      perWorld: 10
      global: 10

    # assign "VIP.Town" permissions as a per-world permission to your VIP users on Town world.
    # when this permission is found (and you set it up so it's only applied on world Town), perWorld
    # limits are 3 and global is 4
    limit3:
      permissions: [VIP.Town]
      perWorld: 3
      global: 4
```

Another way to do it instead of permissions you have to setup and assign unique to each group/world would be just to define some limits like:

```
homeLimits:
  permission:
    limit1:
      permissions: [hspLimit1]
      perWorld: 3
      global: 4
```

Then on world where you want these limits to apply to your VIPs, you give them the "hspLimit1" permission - which you might choose to use across 2 or 3 worlds. Or you might give "hspStaff" permission to your staff on all worlds, so their limits apply everywhere - whatever you like.
